modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="spoonful_of_sugar"
version="1.1.0"
displayName="Spoonful_of_sugar"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Kritcharon, MCreator"

[[dependencies.spoonful_of_sugar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




